// Code generated by new-blok generate; DO NOT EDIT.
package fixture

import "github.com/well-prado/new-blok/flow"

type LineRef struct{ value flow.Ref[Line] }

func LineFields(value flow.Ref[Line]) LineRef { return LineRef{value: value} }

func (r LineRef) SKU() flow.Ref[string] { return flow.Select[Line, string](r.value, "sku") }

func (r LineRef) TotalCents() flow.Ref[int64] { return flow.Select[Line, int64](r.value, "TotalCents") }

func (r LineRef) Total() flow.Ref[int64] { return flow.Select[Line, int64](r.value, "total_cents") }

type LineArgs struct {
	SKU        flow.Ref[string]
	TotalCents flow.Ref[int64]
	Total      flow.Ref[int64]
	Secret     flow.Ref[string]
}
