#!/bin/bash
# gate.sh <worktree> <logdir> : full RULES.md gate, one line per step
set -u
cd "$1" || { echo "gate: cannot cd to $1" >&2; exit 2; }
[ "$(git rev-parse --show-toplevel 2>/dev/null)" = "$(cd "$1" && pwd -P)" ] || { echo "gate: $1 is not a worktree root" >&2; exit 2; }
L=$2; mkdir -p "$L"
echo "head $(git rev-parse HEAD) go $(go version | awk '{print $3}')" > "$L/summary"
step() { n=$1; shift; if "$@" > "$L/$n.log" 2>&1; then echo "PASS $n" >> "$L/summary"; else echo "FAIL $n" >> "$L/summary"; fi; }
step gofmt bash -c 'out=$(gofmt -l .); echo "$out"; [ -z "$out" ]'
step diffcheck git diff --check origin/main...HEAD
step modverify go mod verify
step vet go vet ./...
step vet-win-arm64 env GOOS=windows GOARCH=arm64 go vet ./...
step vet-win-amd64 env GOOS=windows GOARCH=amd64 go vet ./...
step build go build ./...
step build-nocgo env CGO_ENABLED=0 go build ./...
step test go test -count=1 ./...
step race go test -race -count=1 ./...
echo DONE >> "$L/summary"
