package devtool

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"go/parser"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/well-prado/new-blok/internal/diagnostic"
	"github.com/well-prado/new-blok/internal/generate"
	"github.com/well-prado/new-blok/internal/tooling/graphcheck"
)

// Check names, in the order blok check runs them. The slow toolchain check
// runs last, so an interrupt during it still reports every static result.
const (
	CheckProject       = "project"
	CheckNodeImports   = "node-imports"
	CheckBindings      = "bindings"
	CheckWorkflowSteps = "workflow-steps"
	CheckGoVet         = "go-vet"
)

// generatedHeader marks files blok generate owns.
const generatedHeader = "// Code generated by new-blok generate; DO NOT EDIT."

// Options select the project and toolchain a command uses.
type Options struct {
	// Root is the project directory.
	Root string
	// Go is the go command; "go" when empty.
	Go string
	// Source discovers the project; DirectorySource when nil.
	Source ProjectSource
	// Env is the environment the go command starts from; os.Environ() when
	// nil. Toolchain, proxy, module-mode and workspace settings in it are
	// always replaced (goEnv).
	Env []string

	// onLine, for this package's tests, sees every line the go command
	// writes, on the goroutine that reads it.
	onLine func(stream string, line []byte)
}

func (o Options) observe(stream string, line []byte) {
	if o.onLine != nil {
		o.onLine(stream, line)
	}
}

func (o Options) goBinary() string {
	if o.Go == "" {
		return "go"
	}
	return o.Go
}

func (o Options) source() ProjectSource {
	if o.Source == nil {
		return DirectorySource{}
	}
	return o.Source
}

// Check validates a project without executing it. A context cancellation
// stops it; the report then holds every result found before the stop.
func Check(ctx context.Context, options Options) (report Report) {
	report = Report{Command: "check"}
	found := &diagnostics{}
	toolFailure := false
	defer func() { finish(&report, found, ctx, toolFailure) }()

	workspace, projectProblems, err := options.source().Load(ctx, options.Root)
	report.Project = workspace.project()
	if err != nil {
		if ctx.Err() == nil {
			found.add(diagnostic.Diagnostic{Code: "project_unreadable", Actual: errorText(err), Expected: "a readable project directory", Remediation: "run blok from a readable application directory", Message: "the project could not be read"})
		}
		report.Checks = append(report.Checks, CheckResult{Name: CheckProject, State: stateOf(ctx, true)})
		report.Checks = append(report.Checks, notReached(ctx, CheckNodeImports, CheckBindings, CheckWorkflowSteps, CheckGoVet)...)
		return report
	}
	for _, problem := range projectProblems {
		found.add(problem)
	}
	report.Checks = append(report.Checks, CheckResult{Name: CheckProject, State: stateOf(ctx, len(projectProblems) > 0)})
	if workspace.Module == "" {
		reason := "the project has no go.mod module"
		for _, name := range []string{CheckNodeImports, CheckBindings, CheckWorkflowSteps, CheckGoVet} {
			report.Checks = append(report.Checks, CheckResult{Name: name, State: CheckSkipped, Reason: reason})
		}
		return report
	}

	report.Checks = append(report.Checks, checkNodeImports(ctx, workspace, found))
	report.Checks = append(report.Checks, checkBindings(ctx, workspace, found))
	parsed, parseErr := parseWorkspace(ctx, workspace)
	report.Checks = append(report.Checks, checkWorkflowSteps(ctx, parsed, parseErr, found))
	vet, vetToolFailure := checkGoVet(ctx, options, workspace, found)
	toolFailure = vetToolFailure
	report.Checks = append(report.Checks, vet)
	return report
}

func stateOf(ctx context.Context, failed bool) CheckState {
	switch {
	case ctx.Err() != nil:
		return CheckInterrupted
	case failed:
		return CheckFailed
	}
	return CheckPassed
}

func notReached(ctx context.Context, names ...string) []CheckResult {
	results := make([]CheckResult, len(names))
	for index, name := range names {
		results[index] = CheckResult{Name: name, State: CheckSkipped, Reason: "the project could not be read"}
		if ctx.Err() != nil {
			results[index] = CheckResult{Name: name, State: CheckInterrupted}
		}
	}
	return results
}

// checkNodeImports applies the node-independence rule through graphcheck,
// the same analysis the framework enforces on itself, and locates each
// offending import.
func checkNodeImports(ctx context.Context, workspace Workspace, found *diagnostics) CheckResult {
	if ctx.Err() != nil {
		return CheckResult{Name: CheckNodeImports, State: CheckInterrupted}
	}
	results, err := graphcheck.Check(workspace.Root)
	if err != nil {
		return CheckResult{Name: CheckNodeImports, State: CheckSkipped, Reason: "the import graph could not be read: " + firstLine(relativeText(err.Error(), workspace.Root))}
	}
	failed := false
	for _, result := range results {
		if result.Code != "node_import_forbidden" {
			continue
		}
		failed = true
		found.add(diagnostic.Diagnostic{
			Code:        result.Code,
			Source:      importPosition(workspace, result.Package, result.Import),
			Field:       "import",
			Expected:    "no import of another node's package",
			Actual:      result.Import,
			Remediation: "move the shared code into a package outside nodes/ that both nodes may import, or compose the two nodes in a workflow",
			Message:     result.Message,
		})
	}
	return CheckResult{Name: CheckNodeImports, State: stateOf(ctx, failed)}
}

// importPosition is where the package at importPath imports imported.
func importPosition(workspace Workspace, importPath, imported string) string {
	for _, item := range workspace.Packages {
		if item.ImportPath != importPath {
			continue
		}
		for _, name := range item.Files {
			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, name, readOrNil(filepath.Join(workspace.Root, filepath.FromSlash(name))), parser.ImportsOnly)
			if err != nil {
				continue
			}
			for _, spec := range file.Imports {
				if value, err := strconv.Unquote(spec.Path.Value); err == nil && value == imported {
					at := fset.Position(spec.Pos())
					return at.Filename + ":" + strconv.Itoa(at.Line) + ":" + strconv.Itoa(at.Column)
				}
			}
		}
		return item.Dir
	}
	return strings.TrimPrefix(strings.TrimPrefix(importPath, workspace.Module), "/")
}

func readOrNil(name string) []byte {
	data, err := readBounded(name, MaxSourceFileBytes)
	if err != nil {
		return []byte{}
	}
	return data
}

// checkBindings regenerates the manifest's typed bindings in memory, exactly
// as blok generate would, and compares them with the committed file.
func checkBindings(ctx context.Context, workspace Workspace, found *diagnostics) CheckResult {
	if ctx.Err() != nil {
		return CheckResult{Name: CheckBindings, State: CheckInterrupted}
	}
	if workspace.Manifest == nil || workspace.Manifest.Types == "" {
		return CheckResult{Name: CheckBindings, State: CheckSkipped, Reason: "blok.json names no types file"}
	}
	types := path.Clean(workspace.Manifest.Types)
	bindings := path.Join(path.Dir(types), "bindings_gen.go")
	source, err := readBounded(filepath.Join(workspace.Root, filepath.FromSlash(types)), MaxSourceFileBytes)
	if err != nil {
		found.add(diagnostic.Diagnostic{Code: "bindings_types_missing", Source: types, Field: "types", Expected: "the Go types file blok.json names", Actual: errorText(err), Remediation: "restore the types file, or point blok.json's types at the file that declares the node's input and output", Message: "the types file blok.json names cannot be read"})
		return CheckResult{Name: CheckBindings, State: CheckFailed}
	}
	generated, err := generate.Source(source, generate.Options{})
	if err != nil {
		found.add(diagnostic.Diagnostic{Code: "bindings_generate_failed", Source: types, Expected: "types blok generate supports", Actual: relativeText(err.Error(), workspace.Root), Remediation: "fix the types file so blok generate accepts it, then run blok generate", Message: "the typed bindings cannot be generated from the types file"})
		return CheckResult{Name: CheckBindings, State: CheckFailed}
	}
	existing, err := readBounded(filepath.Join(workspace.Root, filepath.FromSlash(bindings)), MaxSourceFileBytes)
	switch {
	case errors.Is(err, os.ErrNotExist):
		found.add(diagnostic.Diagnostic{Code: "bindings_missing", Source: bindings, Expected: "generated bindings beside the types file", Actual: "missing", Remediation: "run blok generate", Message: "the typed bindings have not been generated"})
	case err != nil:
		found.add(diagnostic.Diagnostic{Code: "bindings_missing", Source: bindings, Expected: "generated bindings beside the types file", Actual: errorText(err), Remediation: "make the bindings file readable, then run blok generate", Message: "the typed bindings cannot be read"})
	case !bytes.HasPrefix(existing, []byte(generatedHeader)):
		found.add(diagnostic.Diagnostic{Code: "bindings_not_generated", Source: bindings, Expected: generatedHeader, Actual: "a hand-written file", Remediation: "move the hand-written code to another file, delete this one, then run blok generate", Message: "the bindings file was not written by blok generate"})
	case !bytes.Equal(existing, generated):
		found.add(diagnostic.Diagnostic{Code: "bindings_stale", Source: bindings, Expected: "bindings generated from " + types, Actual: "out of date", Remediation: "run blok generate", Message: "the typed bindings are stale"})
	default:
		return CheckResult{Name: CheckBindings, State: stateOf(ctx, false)}
	}
	return CheckResult{Name: CheckBindings, State: CheckFailed}
}

// checkWorkflowSteps applies the step-id rules flow.Define enforces to every
// workflow whose builder calls name literal ids.
func checkWorkflowSteps(ctx context.Context, parsed *source, parseErr error, found *diagnostics) CheckResult {
	if parseErr != nil || ctx.Err() != nil {
		return CheckResult{Name: CheckWorkflowSteps, State: CheckInterrupted}
	}
	extracted := parsed.extract()
	result := CheckResult{Name: CheckWorkflowSteps, Unresolved: len(parsed.parseErrors)}
	failed := false
	for _, workflow := range extracted.workflows {
		result.Unresolved += len(workflow.unresolved)
		for _, problem := range parsed.stepDiagnostics(workflow) {
			failed = true
			found.add(problem)
		}
	}
	result.State = stateOf(ctx, failed)
	if len(parsed.parseErrors) > 0 {
		result.Reason = "files that do not parse are not read; go-vet reports them"
	}
	return result
}

// vetPosition matches go vet -json's posn: path:line[:col].
var vetPosition = regexp.MustCompile(`^(.*\.go)(:\d+(?::\d+)?)$`)

// checkGoVet type-checks and vets every package with the go toolchain. It
// compiles the packages but runs none of them, and never downloads (goEnv).
func checkGoVet(ctx context.Context, options Options, workspace Workspace, found *diagnostics) (CheckResult, bool) {
	if ctx.Err() != nil {
		return CheckResult{Name: CheckGoVet, State: CheckInterrupted}, false
	}
	var stdout bytes.Buffer
	toolchain := &goDiagnostics{root: workspace.Root}
	run, err := runGo(ctx, goCommand{
		binary: options.goBinary(), dir: workspace.Root, args: []string{"vet", "-json", "./..."}, env: options.Env,
		stdout: func(line []byte) {
			options.observe("stdout", line)
			stdout.Write(line)
			stdout.WriteByte('\n')
		},
		stderr: func(line []byte) {
			options.observe("stderr", line)
			toolchain.line(string(line))
		},
	})
	if errors.Is(err, errToolUnavailable) {
		found.add(toolUnavailable(options.goBinary(), err))
		return CheckResult{Name: CheckGoVet, State: CheckSkipped, Reason: "the go command could not be started"}, true
	}
	if err != nil && ctx.Err() == nil {
		found.add(toolchainError(err.Error()))
	}
	problems := append(toolchain.result(), vetFindings(stdout.Bytes(), workspace.Root)...)
	if ctx.Err() == nil && run.exitCode != 0 && len(problems) == 0 {
		problems = append(problems, toolchainError("go vet exited with status "+strconv.Itoa(run.exitCode)+" without a diagnostic"))
	}
	for _, problem := range dedupe(problems) {
		found.add(problem)
	}
	return CheckResult{Name: CheckGoVet, State: stateOf(ctx, len(problems) > 0)}, false
}

// vetFindings decodes go vet -json's stream: one object per package, keyed
// by import path and analyzer.
func vetFindings(stream []byte, root string) []diagnostic.Diagnostic {
	type finding struct {
		Posn    string `json:"posn"`
		Message string `json:"message"`
	}
	var problems []diagnostic.Diagnostic
	decoder := json.NewDecoder(bytes.NewReader(stream))
	for {
		var packages map[string]map[string]json.RawMessage
		if err := decoder.Decode(&packages); err != nil {
			break
		}
		for _, analyzers := range packages {
			for analyzer, raw := range analyzers {
				var findings []finding
				if json.Unmarshal(raw, &findings) != nil {
					continue
				}
				for _, item := range findings {
					position := item.Posn
					if match := vetPosition.FindStringSubmatch(position); match != nil {
						position = relativePath(match[1], root) + match[2]
					}
					problems = append(problems, diagnostic.Diagnostic{Code: "go_vet_finding", Source: position, Field: analyzer, Expected: "no " + analyzer + " finding", Actual: relativeText(item.Message, root), Remediation: "fix the code go vet's " + analyzer + " analyzer reports at this position", Message: "go vet reported a likely mistake"})
				}
			}
		}
	}
	return problems
}

func dedupe(items []diagnostic.Diagnostic) []diagnostic.Diagnostic {
	seen := map[diagnostic.Diagnostic]bool{}
	result := items[:0:0]
	for _, item := range items {
		if !seen[item] {
			seen[item] = true
			result = append(result, item)
		}
	}
	return result
}

// relativePath makes a path under root relative and slash-separated, so a
// report does not depend on where the project lives.
func relativePath(name, root string) string {
	for _, base := range roots(root) {
		if relative, err := filepath.Rel(base, name); err == nil && filepath.IsAbs(name) && relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
			return filepath.ToSlash(relative)
		}
	}
	return filepath.ToSlash(name)
}

// relativeText removes the absolute root from free text.
func relativeText(text, root string) string {
	for _, base := range roots(root) {
		text = strings.ReplaceAll(text, base+string(filepath.Separator), "")
		text = strings.ReplaceAll(text, base, ".")
	}
	return text
}

// roots is root and, when it differs, its symlink-resolved form (macOS
// reports /private/tmp for /tmp).
func roots(root string) []string {
	result := []string{root}
	if resolved, err := filepath.EvalSymlinks(root); err == nil && resolved != root {
		result = append(result, resolved)
	}
	return result
}

func firstLine(text string) string {
	line, _, _ := strings.Cut(text, "\n")
	return line
}
