// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: runtime.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorClass int32

const (
	ErrorClass_ERROR_CLASS_UNSPECIFIED ErrorClass = 0
	ErrorClass_INVALID_INPUT           ErrorClass = 1
	ErrorClass_NODE_ERROR              ErrorClass = 2
	ErrorClass_TRANSIENT               ErrorClass = 3
	ErrorClass_UNCERTAIN               ErrorClass = 4
	ErrorClass_CANCELED                ErrorClass = 5
	ErrorClass_DEADLINE_EXCEEDED       ErrorClass = 6
)

// Enum value maps for ErrorClass.
var (
	ErrorClass_name = map[int32]string{
		0: "ERROR_CLASS_UNSPECIFIED",
		1: "INVALID_INPUT",
		2: "NODE_ERROR",
		3: "TRANSIENT",
		4: "UNCERTAIN",
		5: "CANCELED",
		6: "DEADLINE_EXCEEDED",
	}
	ErrorClass_value = map[string]int32{
		"ERROR_CLASS_UNSPECIFIED": 0,
		"INVALID_INPUT":           1,
		"NODE_ERROR":              2,
		"TRANSIENT":               3,
		"UNCERTAIN":               4,
		"CANCELED":                5,
		"DEADLINE_EXCEEDED":       6,
	}
)

func (x ErrorClass) Enum() *ErrorClass {
	p := new(ErrorClass)
	*p = x
	return p
}

func (x ErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[0].Descriptor()
}

func (ErrorClass) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[0]
}

func (x ErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorClass.Descriptor instead.
func (ErrorClass) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

type Limits struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxFrameBytes      uint32                 `protobuf:"varint,1,opt,name=max_frame_bytes,json=maxFrameBytes,proto3" json:"max_frame_bytes,omitempty"`
	MaxBlobBytes       uint32                 `protobuf:"varint,2,opt,name=max_blob_bytes,json=maxBlobBytes,proto3" json:"max_blob_bytes,omitempty"`
	MaxConcurrentCalls uint32                 `protobuf:"varint,3,opt,name=max_concurrent_calls,json=maxConcurrentCalls,proto3" json:"max_concurrent_calls,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *Limits) GetMaxFrameBytes() uint32 {
	if x != nil {
		return x.MaxFrameBytes
	}
	return 0
}

func (x *Limits) GetMaxBlobBytes() uint32 {
	if x != nil {
		return x.MaxBlobBytes
	}
	return 0
}

func (x *Limits) GetMaxConcurrentCalls() uint32 {
	if x != nil {
		return x.MaxConcurrentCalls
	}
	return 0
}

type Hello struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protocol       string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Major          uint32                 `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor          uint32                 `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	ArtifactDigest string                 `protobuf:"bytes,4,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	CatalogDigest  string                 `protobuf:"bytes,5,opt,name=catalog_digest,json=catalogDigest,proto3" json:"catalog_digest,omitempty"`
	Generation     uint64                 `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	Capabilities   []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Limits         *Limits                `protobuf:"bytes,8,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Hello) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Hello) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Hello) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

func (x *Hello) GetCatalogDigest() string {
	if x != nil {
		return x.CatalogDigest
	}
	return ""
}

func (x *Hello) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Hello) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Hello                 `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *Ready) GetContract() *Hello {
	if x != nil {
		return x.Contract
	}
	return nil
}

type BlobRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRef) Reset() {
	*x = BlobRef{}
	mi := &file_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRef) ProtoMessage() {}

func (x *BlobRef) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRef.ProtoReflect.Descriptor instead.
func (*BlobRef) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *BlobRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *BlobRef) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Call struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CallId            string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	AttemptId         string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Generation        uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Node              string                 `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	NodeVersion       string                 `protobuf:"bytes,5,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	DeadlineUnixNanos int64                  `protobuf:"varint,7,opt,name=deadline_unix_nanos,json=deadlineUnixNanos,proto3" json:"deadline_unix_nanos,omitempty"`
	Input             []byte                 `protobuf:"bytes,8,opt,name=input,proto3" json:"input,omitempty"`
	Blobs             []*BlobRef             `protobuf:"bytes,9,rep,name=blobs,proto3" json:"blobs,omitempty"`
	Principal         string                 `protobuf:"bytes,10,opt,name=principal,proto3" json:"principal,omitempty"`
	Capabilities      []string               `protobuf:"bytes,11,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *Call) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Call) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Call) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Call) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Call) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *Call) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Call) GetDeadlineUnixNanos() int64 {
	if x != nil {
		return x.DeadlineUnixNanos
	}
	return 0
}

func (x *Call) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Call) GetBlobs() []*BlobRef {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *Call) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Call) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *Cancel) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Cancel) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Cancel) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        uint32                 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *Drain) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type RemoteError struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Class          ErrorClass             `protobuf:"varint,1,opt,name=class,proto3,enum=blok.runtime.v1.ErrorClass" json:"class,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable      bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoteError) Reset() {
	*x = RemoteError{}
	mi := &file_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteError) ProtoMessage() {}

func (x *RemoteError) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteError.ProtoReflect.Descriptor instead.
func (*RemoteError) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *RemoteError) GetClass() ErrorClass {
	if x != nil {
		return x.Class
	}
	return ErrorClass_ERROR_CLASS_UNSPECIFIED
}

func (x *RemoteError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RemoteError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoteError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *RemoteError) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Output        []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         *RemoteError           `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *Result) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Result) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Result) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Result) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Result) GetError() *RemoteError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Log is scoped to one active call and is optional observability data. Workers
// may drop records after their per-call bound; it never changes call outcome.
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	AttrsJson     []byte                 `protobuf:"bytes,6,opt,name=attrs_json,json=attrsJson,proto3" json:"attrs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *Log) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Log) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Log) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log) GetAttrsJson() []byte {
	if x != nil {
		return x.AttrsJson
	}
	return nil
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Hello
	//	*Frame_Ready
	//	*Frame_Call
	//	*Frame_Result
	//	*Frame_Cancel
	//	*Frame_Drain
	//	*Frame_Log
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Frame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Frame) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Body.(*Frame_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *Frame) GetCall() *Call {
	if x != nil {
		if x, ok := x.Body.(*Frame_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Frame) GetResult() *Result {
	if x != nil {
		if x, ok := x.Body.(*Frame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Frame) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Body.(*Frame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Frame) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Body.(*Frame_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *Frame) GetLog() *Log {
	if x != nil {
		if x, ok := x.Body.(*Frame_Log); ok {
			return x.Log
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Frame_Ready struct {
	Ready *Ready `protobuf:"bytes,2,opt,name=ready,proto3,oneof"`
}

type Frame_Call struct {
	Call *Call `protobuf:"bytes,3,opt,name=call,proto3,oneof"`
}

type Frame_Result struct {
	Result *Result `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

type Frame_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,5,opt,name=cancel,proto3,oneof"`
}

type Frame_Drain struct {
	Drain *Drain `protobuf:"bytes,6,opt,name=drain,proto3,oneof"`
}

type Frame_Log struct {
	Log *Log `protobuf:"bytes,7,opt,name=log,proto3,oneof"`
}

func (*Frame_Hello) isFrame_Body() {}

func (*Frame_Ready) isFrame_Body() {}

func (*Frame_Call) isFrame_Body() {}

func (*Frame_Result) isFrame_Body() {}

func (*Frame_Cancel) isFrame_Body() {}

func (*Frame_Drain) isFrame_Body() {}

func (*Frame_Log) isFrame_Body() {}

var File_runtime_proto protoreflect.FileDescriptor

const file_runtime_proto_rawDesc = "" +
	"\n" +
	"\rruntime.proto\x12\x0fblok.runtime.v1\"\x88\x01\n" +
	"\x06Limits\x12&\n" +
	"\x0fmax_frame_bytes\x18\x01 \x01(\rR\rmaxFrameBytes\x12$\n" +
	"\x0emax_blob_bytes\x18\x02 \x01(\rR\fmaxBlobBytes\x120\n" +
	"\x14max_concurrent_calls\x18\x03 \x01(\rR\x12maxConcurrentCalls\"\x94\x02\n" +
	"\x05Hello\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05major\x18\x02 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x03 \x01(\rR\x05minor\x12'\n" +
	"\x0fartifact_digest\x18\x04 \x01(\tR\x0eartifactDigest\x12%\n" +
	"\x0ecatalog_digest\x18\x05 \x01(\tR\rcatalogDigest\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x04R\n" +
	"generation\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12/\n" +
	"\x06limits\x18\b \x01(\v2\x17.blok.runtime.v1.LimitsR\x06limits\";\n" +
	"\x05Ready\x122\n" +
	"\bcontract\x18\x01 \x01(\v2\x16.blok.runtime.v1.HelloR\bcontract\"5\n" +
	"\aBlobRef\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\xf6\x02\n" +
	"\x04Call\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\x12!\n" +
	"\fnode_version\x18\x05 \x01(\tR\vnodeVersion\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12.\n" +
	"\x13deadline_unix_nanos\x18\a \x01(\x03R\x11deadlineUnixNanos\x12\x14\n" +
	"\x05input\x18\b \x01(\fR\x05input\x12.\n" +
	"\x05blobs\x18\t \x03(\v2\x18.blok.runtime.v1.BlobRefR\x05blobs\x12\x1c\n" +
	"\tprincipal\x18\n" +
	" \x01(\tR\tprincipal\x12\"\n" +
	"\fcapabilities\x18\v \x03(\tR\fcapabilities\"`\n" +
	"\x06Cancel\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\"\x1f\n" +
	"\x05Drain\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\rR\x06reason\"\xb5\x01\n" +
	"\vRemoteError\x121\n" +
	"\x05class\x18\x01 \x01(\x0e2\x1b.blok.runtime.v1.ErrorClassR\x05class\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xac\x01\n" +
	"\x06Result\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\x122\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.blok.runtime.v1.RemoteErrorR\x05error\"\xac\x01\n" +
	"\x03Log\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"attrs_json\x18\x06 \x01(\fR\tattrsJson\"\xdc\x02\n" +
	"\x05Frame\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.blok.runtime.v1.HelloH\x00R\x05hello\x12.\n" +
	"\x05ready\x18\x02 \x01(\v2\x16.blok.runtime.v1.ReadyH\x00R\x05ready\x12+\n" +
	"\x04call\x18\x03 \x01(\v2\x15.blok.runtime.v1.CallH\x00R\x04call\x121\n" +
	"\x06result\x18\x04 \x01(\v2\x17.blok.runtime.v1.ResultH\x00R\x06result\x121\n" +
	"\x06cancel\x18\x05 \x01(\v2\x17.blok.runtime.v1.CancelH\x00R\x06cancel\x12.\n" +
	"\x05drain\x18\x06 \x01(\v2\x16.blok.runtime.v1.DrainH\x00R\x05drain\x12(\n" +
	"\x03log\x18\a \x01(\v2\x14.blok.runtime.v1.LogH\x00R\x03logB\x06\n" +
	"\x04body*\x8f\x01\n" +
	"\n" +
	"ErrorClass\x12\x1b\n" +
	"\x17ERROR_CLASS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rINVALID_INPUT\x10\x01\x12\x0e\n" +
	"\n" +
	"NODE_ERROR\x10\x02\x12\r\n" +
	"\tTRANSIENT\x10\x03\x12\r\n" +
	"\tUNCERTAIN\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x05\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x062\x81\x01\n" +
	"\x06Worker\x12=\n" +
	"\aConnect\x12\x16.blok.runtime.v1.Frame\x1a\x16.blok.runtime.v1.Frame(\x010\x01\x128\n" +
	"\x06Invoke\x12\x15.blok.runtime.v1.Call\x1a\x17.blok.runtime.v1.ResultB;Z9github.com/well-prado/new-blok/contract/runtime/wire;wireb\x06proto3"

var (
	file_runtime_proto_rawDescOnce sync.Once
	file_runtime_proto_rawDescData []byte
)

func file_runtime_proto_rawDescGZIP() []byte {
	file_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)))
	})
	return file_runtime_proto_rawDescData
}

var file_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_runtime_proto_goTypes = []any{
	(ErrorClass)(0),     // 0: blok.runtime.v1.ErrorClass
	(*Limits)(nil),      // 1: blok.runtime.v1.Limits
	(*Hello)(nil),       // 2: blok.runtime.v1.Hello
	(*Ready)(nil),       // 3: blok.runtime.v1.Ready
	(*BlobRef)(nil),     // 4: blok.runtime.v1.BlobRef
	(*Call)(nil),        // 5: blok.runtime.v1.Call
	(*Cancel)(nil),      // 6: blok.runtime.v1.Cancel
	(*Drain)(nil),       // 7: blok.runtime.v1.Drain
	(*RemoteError)(nil), // 8: blok.runtime.v1.RemoteError
	(*Result)(nil),      // 9: blok.runtime.v1.Result
	(*Log)(nil),         // 10: blok.runtime.v1.Log
	(*Frame)(nil),       // 11: blok.runtime.v1.Frame
}
var file_runtime_proto_depIdxs = []int32{
	1,  // 0: blok.runtime.v1.Hello.limits:type_name -> blok.runtime.v1.Limits
	2,  // 1: blok.runtime.v1.Ready.contract:type_name -> blok.runtime.v1.Hello
	4,  // 2: blok.runtime.v1.Call.blobs:type_name -> blok.runtime.v1.BlobRef
	0,  // 3: blok.runtime.v1.RemoteError.class:type_name -> blok.runtime.v1.ErrorClass
	8,  // 4: blok.runtime.v1.Result.error:type_name -> blok.runtime.v1.RemoteError
	2,  // 5: blok.runtime.v1.Frame.hello:type_name -> blok.runtime.v1.Hello
	3,  // 6: blok.runtime.v1.Frame.ready:type_name -> blok.runtime.v1.Ready
	5,  // 7: blok.runtime.v1.Frame.call:type_name -> blok.runtime.v1.Call
	9,  // 8: blok.runtime.v1.Frame.result:type_name -> blok.runtime.v1.Result
	6,  // 9: blok.runtime.v1.Frame.cancel:type_name -> blok.runtime.v1.Cancel
	7,  // 10: blok.runtime.v1.Frame.drain:type_name -> blok.runtime.v1.Drain
	10, // 11: blok.runtime.v1.Frame.log:type_name -> blok.runtime.v1.Log
	11, // 12: blok.runtime.v1.Worker.Connect:input_type -> blok.runtime.v1.Frame
	5,  // 13: blok.runtime.v1.Worker.Invoke:input_type -> blok.runtime.v1.Call
	11, // 14: blok.runtime.v1.Worker.Connect:output_type -> blok.runtime.v1.Frame
	9,  // 15: blok.runtime.v1.Worker.Invoke:output_type -> blok.runtime.v1.Result
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_runtime_proto_init() }
func file_runtime_proto_init() {
	if File_runtime_proto != nil {
		return
	}
	file_runtime_proto_msgTypes[10].OneofWrappers = []any{
		(*Frame_Hello)(nil),
		(*Frame_Ready)(nil),
		(*Frame_Call)(nil),
		(*Frame_Result)(nil),
		(*Frame_Cancel)(nil),
		(*Frame_Drain)(nil),
		(*Frame_Log)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_proto_depIdxs,
		EnumInfos:         file_runtime_proto_enumTypes,
		MessageInfos:      file_runtime_proto_msgTypes,
	}.Build()
	File_runtime_proto = out.File
	file_runtime_proto_goTypes = nil
	file_runtime_proto_depIdxs = nil
}
