// Synthetic service for trigger/grpc tests: the conformance order, kinds
// the mapping supports, and kinds it refuses at startup.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: orders.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orders_Place_FullMethodName   = "/newblok.test.orders.v1.Orders/Place"
	Orders_Inspect_FullMethodName = "/newblok.test.orders.v1.Orders/Inspect"
	Orders_Watch_FullMethodName   = "/newblok.test.orders.v1.Orders/Watch"
	Orders_Choose_FullMethodName  = "/newblok.test.orders.v1.Orders/Choose"
	Orders_Count_FullMethodName   = "/newblok.test.orders.v1.Orders/Count"
	Orders_Label_FullMethodName   = "/newblok.test.orders.v1.Orders/Label"
	Orders_Stamp_FullMethodName   = "/newblok.test.orders.v1.Orders/Stamp"
	Orders_Walk_FullMethodName    = "/newblok.test.orders.v1.Orders/Walk"
	Orders_Fill_FullMethodName    = "/newblok.test.orders.v1.Orders/Fill"
)

// OrdersClient is the client API for Orders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrdersClient interface {
	Place(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Placed, error)
	Inspect(ctx context.Context, in *Kinds, opts ...grpc.CallOption) (*Kinds, error)
	Watch(ctx context.Context, in *Order, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Placed], error)
	Choose(ctx context.Context, in *WithOneof, opts ...grpc.CallOption) (*Placed, error)
	Count(ctx context.Context, in *WithUint64, opts ...grpc.CallOption) (*Placed, error)
	Label(ctx context.Context, in *WithMap, opts ...grpc.CallOption) (*Placed, error)
	Stamp(ctx context.Context, in *WithTimestamp, opts ...grpc.CallOption) (*Placed, error)
	Walk(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Node, error)
	Fill(ctx context.Context, in *Rows, opts ...grpc.CallOption) (*Node, error)
}

type ordersClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersClient(cc grpc.ClientConnInterface) OrdersClient {
	return &ordersClient{cc}
}

func (c *ordersClient) Place(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Placed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Placed)
	err := c.cc.Invoke(ctx, Orders_Place_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) Inspect(ctx context.Context, in *Kinds, opts ...grpc.CallOption) (*Kinds, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Kinds)
	err := c.cc.Invoke(ctx, Orders_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) Watch(ctx context.Context, in *Order, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Placed], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Orders_ServiceDesc.Streams[0], Orders_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Order, Placed]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orders_WatchClient = grpc.ServerStreamingClient[Placed]

func (c *ordersClient) Choose(ctx context.Context, in *WithOneof, opts ...grpc.CallOption) (*Placed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Placed)
	err := c.cc.Invoke(ctx, Orders_Choose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) Count(ctx context.Context, in *WithUint64, opts ...grpc.CallOption) (*Placed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Placed)
	err := c.cc.Invoke(ctx, Orders_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) Label(ctx context.Context, in *WithMap, opts ...grpc.CallOption) (*Placed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Placed)
	err := c.cc.Invoke(ctx, Orders_Label_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) Stamp(ctx context.Context, in *WithTimestamp, opts ...grpc.CallOption) (*Placed, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Placed)
	err := c.cc.Invoke(ctx, Orders_Stamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) Walk(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, Orders_Walk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersClient) Fill(ctx context.Context, in *Rows, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, Orders_Fill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdersServer is the server API for Orders service.
// All implementations must embed UnimplementedOrdersServer
// for forward compatibility.
type OrdersServer interface {
	Place(context.Context, *Order) (*Placed, error)
	Inspect(context.Context, *Kinds) (*Kinds, error)
	Watch(*Order, grpc.ServerStreamingServer[Placed]) error
	Choose(context.Context, *WithOneof) (*Placed, error)
	Count(context.Context, *WithUint64) (*Placed, error)
	Label(context.Context, *WithMap) (*Placed, error)
	Stamp(context.Context, *WithTimestamp) (*Placed, error)
	Walk(context.Context, *Node) (*Node, error)
	Fill(context.Context, *Rows) (*Node, error)
	mustEmbedUnimplementedOrdersServer()
}

// UnimplementedOrdersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdersServer struct{}

func (UnimplementedOrdersServer) Place(context.Context, *Order) (*Placed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Place not implemented")
}
func (UnimplementedOrdersServer) Inspect(context.Context, *Kinds) (*Kinds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedOrdersServer) Watch(*Order, grpc.ServerStreamingServer[Placed]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedOrdersServer) Choose(context.Context, *WithOneof) (*Placed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Choose not implemented")
}
func (UnimplementedOrdersServer) Count(context.Context, *WithUint64) (*Placed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedOrdersServer) Label(context.Context, *WithMap) (*Placed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Label not implemented")
}
func (UnimplementedOrdersServer) Stamp(context.Context, *WithTimestamp) (*Placed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stamp not implemented")
}
func (UnimplementedOrdersServer) Walk(context.Context, *Node) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Walk not implemented")
}
func (UnimplementedOrdersServer) Fill(context.Context, *Rows) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fill not implemented")
}
func (UnimplementedOrdersServer) mustEmbedUnimplementedOrdersServer() {}
func (UnimplementedOrdersServer) testEmbeddedByValue()                {}

// UnsafeOrdersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdersServer will
// result in compilation errors.
type UnsafeOrdersServer interface {
	mustEmbedUnimplementedOrdersServer()
}

func RegisterOrdersServer(s grpc.ServiceRegistrar, srv OrdersServer) {
	// If the following call pancis, it indicates UnimplementedOrdersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orders_ServiceDesc, srv)
}

func _Orders_Place_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Place(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Place_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Place(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Kinds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Inspect(ctx, req.(*Kinds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Order)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrdersServer).Watch(m, &grpc.GenericServerStream[Order, Placed]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Orders_WatchServer = grpc.ServerStreamingServer[Placed]

func _Orders_Choose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithOneof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Choose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Choose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Choose(ctx, req.(*WithOneof))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithUint64)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Count(ctx, req.(*WithUint64))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_Label_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithMap)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Label(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Label_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Label(ctx, req.(*WithMap))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_Stamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithTimestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Stamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Stamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Stamp(ctx, req.(*WithTimestamp))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_Walk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Walk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Walk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Walk(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orders_Fill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rows)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServer).Fill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orders_Fill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServer).Fill(ctx, req.(*Rows))
	}
	return interceptor(ctx, in, info, handler)
}

// Orders_ServiceDesc is the grpc.ServiceDesc for Orders service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orders_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newblok.test.orders.v1.Orders",
	HandlerType: (*OrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Place",
			Handler:    _Orders_Place_Handler,
		},
		{
			MethodName: "Inspect",
			Handler:    _Orders_Inspect_Handler,
		},
		{
			MethodName: "Choose",
			Handler:    _Orders_Choose_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _Orders_Count_Handler,
		},
		{
			MethodName: "Label",
			Handler:    _Orders_Label_Handler,
		},
		{
			MethodName: "Stamp",
			Handler:    _Orders_Stamp_Handler,
		},
		{
			MethodName: "Walk",
			Handler:    _Orders_Walk_Handler,
		},
		{
			MethodName: "Fill",
			Handler:    _Orders_Fill_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Orders_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orders.proto",
}
