// Synthetic service for trigger/grpc tests: the conformance order, kinds
// the mapping supports, and kinds it refuses at startup.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: orders.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_RED         Color = 1
	Color_COLOR_BLUE        Color = 2
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "COLOR_RED",
		2: "COLOR_BLUE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_RED":         1,
		"COLOR_BLUE":        2,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_orders_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_orders_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *string                `protobuf:"bytes,1,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	Quantity      *int32                 `protobuf:"varint,2,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Principal     *string                `protobuf:"bytes,3,opt,name=principal,proto3,oneof" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *Order) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *Order) GetPrincipal() string {
	if x != nil && x.Principal != nil {
		return *x.Principal
	}
	return ""
}

type Placed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Echo          *Order                 `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placed) Reset() {
	*x = Placed{}
	mi := &file_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placed) ProtoMessage() {}

func (x *Placed) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placed.ProtoReflect.Descriptor instead.
func (*Placed) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Placed) GetEcho() *Order {
	if x != nil {
		return x.Echo
	}
	return nil
}

// Kinds covers every field kind the mapping supports.
type Kinds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Small         int32                  `protobuf:"varint,3,opt,name=small,proto3" json:"small,omitempty"`
	Large         int64                  `protobuf:"varint,4,opt,name=large,proto3" json:"large,omitempty"`
	Count         uint32                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Ratio         float64                `protobuf:"fixed64,6,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Blob          []byte                 `protobuf:"bytes,7,opt,name=blob,proto3" json:"blob,omitempty"`
	Color         Color                  `protobuf:"varint,8,opt,name=color,proto3,enum=newblok.test.orders.v1.Color" json:"color,omitempty"`
	Order         *Order                 `protobuf:"bytes,9,opt,name=order,proto3" json:"order,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Lines         []*Order               `protobuf:"bytes,11,rep,name=lines,proto3" json:"lines,omitempty"`
	Note          *string                `protobuf:"bytes,12,opt,name=note,proto3,oneof" json:"note,omitempty"`
	Counts        []int32                `protobuf:"varint,13,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kinds) Reset() {
	*x = Kinds{}
	mi := &file_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kinds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kinds) ProtoMessage() {}

func (x *Kinds) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kinds.ProtoReflect.Descriptor instead.
func (*Kinds) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{2}
}

func (x *Kinds) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Kinds) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Kinds) GetSmall() int32 {
	if x != nil {
		return x.Small
	}
	return 0
}

func (x *Kinds) GetLarge() int64 {
	if x != nil {
		return x.Large
	}
	return 0
}

func (x *Kinds) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Kinds) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *Kinds) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *Kinds) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *Kinds) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *Kinds) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Kinds) GetLines() []*Order {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Kinds) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *Kinds) GetCounts() []int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type WithOneof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choice:
	//
	//	*WithOneof_A
	//	*WithOneof_B
	Choice        isWithOneof_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithOneof) Reset() {
	*x = WithOneof{}
	mi := &file_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithOneof) ProtoMessage() {}

func (x *WithOneof) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithOneof.ProtoReflect.Descriptor instead.
func (*WithOneof) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{3}
}

func (x *WithOneof) GetChoice() isWithOneof_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *WithOneof) GetA() string {
	if x != nil {
		if x, ok := x.Choice.(*WithOneof_A); ok {
			return x.A
		}
	}
	return ""
}

func (x *WithOneof) GetB() int32 {
	if x != nil {
		if x, ok := x.Choice.(*WithOneof_B); ok {
			return x.B
		}
	}
	return 0
}

type isWithOneof_Choice interface {
	isWithOneof_Choice()
}

type WithOneof_A struct {
	A string `protobuf:"bytes,1,opt,name=a,proto3,oneof"`
}

type WithOneof_B struct {
	B int32 `protobuf:"varint,2,opt,name=b,proto3,oneof"`
}

func (*WithOneof_A) isWithOneof_Choice() {}

func (*WithOneof_B) isWithOneof_Choice() {}

type WithUint64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Big           uint64                 `protobuf:"varint,1,opt,name=big,proto3" json:"big,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithUint64) Reset() {
	*x = WithUint64{}
	mi := &file_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithUint64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithUint64) ProtoMessage() {}

func (x *WithUint64) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithUint64.ProtoReflect.Descriptor instead.
func (*WithUint64) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{4}
}

func (x *WithUint64) GetBig() uint64 {
	if x != nil {
		return x.Big
	}
	return 0
}

type WithMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithMap) Reset() {
	*x = WithMap{}
	mi := &file_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithMap) ProtoMessage() {}

func (x *WithMap) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithMap.ProtoReflect.Descriptor instead.
func (*WithMap) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{5}
}

func (x *WithMap) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type WithTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithTimestamp) Reset() {
	*x = WithTimestamp{}
	mi := &file_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithTimestamp) ProtoMessage() {}

func (x *WithTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithTimestamp.ProtoReflect.Descriptor instead.
func (*WithTimestamp) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{6}
}

func (x *WithTimestamp) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// Node nests itself, for the nesting bound.
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Child         *Node                  `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{7}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetChild() *Node {
	if x != nil {
		return x.Child
	}
	return nil
}

// Wide has many implicit-presence fields, each written with its default.
type Wide struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FieldWithALongName_01 string                 `protobuf:"bytes,1,opt,name=field_with_a_long_name_01,json=fieldWithALongName01,proto3" json:"field_with_a_long_name_01,omitempty"`
	FieldWithALongName_02 string                 `protobuf:"bytes,2,opt,name=field_with_a_long_name_02,json=fieldWithALongName02,proto3" json:"field_with_a_long_name_02,omitempty"`
	FieldWithALongName_03 string                 `protobuf:"bytes,3,opt,name=field_with_a_long_name_03,json=fieldWithALongName03,proto3" json:"field_with_a_long_name_03,omitempty"`
	FieldWithALongName_04 string                 `protobuf:"bytes,4,opt,name=field_with_a_long_name_04,json=fieldWithALongName04,proto3" json:"field_with_a_long_name_04,omitempty"`
	FieldWithALongName_05 string                 `protobuf:"bytes,5,opt,name=field_with_a_long_name_05,json=fieldWithALongName05,proto3" json:"field_with_a_long_name_05,omitempty"`
	FieldWithALongName_06 string                 `protobuf:"bytes,6,opt,name=field_with_a_long_name_06,json=fieldWithALongName06,proto3" json:"field_with_a_long_name_06,omitempty"`
	FieldWithALongName_07 string                 `protobuf:"bytes,7,opt,name=field_with_a_long_name_07,json=fieldWithALongName07,proto3" json:"field_with_a_long_name_07,omitempty"`
	FieldWithALongName_08 string                 `protobuf:"bytes,8,opt,name=field_with_a_long_name_08,json=fieldWithALongName08,proto3" json:"field_with_a_long_name_08,omitempty"`
	FieldWithALongName_09 string                 `protobuf:"bytes,9,opt,name=field_with_a_long_name_09,json=fieldWithALongName09,proto3" json:"field_with_a_long_name_09,omitempty"`
	FieldWithALongName_10 string                 `protobuf:"bytes,10,opt,name=field_with_a_long_name_10,json=fieldWithALongName10,proto3" json:"field_with_a_long_name_10,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Wide) Reset() {
	*x = Wide{}
	mi := &file_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wide) ProtoMessage() {}

func (x *Wide) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wide.ProtoReflect.Descriptor instead.
func (*Wide) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{8}
}

func (x *Wide) GetFieldWithALongName_01() string {
	if x != nil {
		return x.FieldWithALongName_01
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_02() string {
	if x != nil {
		return x.FieldWithALongName_02
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_03() string {
	if x != nil {
		return x.FieldWithALongName_03
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_04() string {
	if x != nil {
		return x.FieldWithALongName_04
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_05() string {
	if x != nil {
		return x.FieldWithALongName_05
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_06() string {
	if x != nil {
		return x.FieldWithALongName_06
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_07() string {
	if x != nil {
		return x.FieldWithALongName_07
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_08() string {
	if x != nil {
		return x.FieldWithALongName_08
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_09() string {
	if x != nil {
		return x.FieldWithALongName_09
	}
	return ""
}

func (x *Wide) GetFieldWithALongName_10() string {
	if x != nil {
		return x.FieldWithALongName_10
	}
	return ""
}

type Rows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Wide                `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rows) Reset() {
	*x = Rows{}
	mi := &file_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rows) ProtoMessage() {}

func (x *Rows) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rows.ProtoReflect.Descriptor instead.
func (*Rows) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{9}
}

func (x *Rows) GetRows() []*Wide {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_orders_proto protoreflect.FileDescriptor

const file_orders_proto_rawDesc = "" +
	"\n" +
	"\forders.proto\x12\x16newblok.test.orders.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"\x05Order\x12\x15\n" +
	"\x03sku\x18\x01 \x01(\tH\x00R\x03sku\x88\x01\x01\x12\x1f\n" +
	"\bquantity\x18\x02 \x01(\x05H\x01R\bquantity\x88\x01\x01\x12!\n" +
	"\tprincipal\x18\x03 \x01(\tH\x02R\tprincipal\x88\x01\x01B\x06\n" +
	"\x04_skuB\v\n" +
	"\t_quantityB\f\n" +
	"\n" +
	"_principal\";\n" +
	"\x06Placed\x121\n" +
	"\x04echo\x18\x01 \x01(\v2\x1d.newblok.test.orders.v1.OrderR\x04echo\"\x8c\x03\n" +
	"\x05Kinds\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x14\n" +
	"\x05small\x18\x03 \x01(\x05R\x05small\x12\x14\n" +
	"\x05large\x18\x04 \x01(\x03R\x05large\x12\x14\n" +
	"\x05count\x18\x05 \x01(\rR\x05count\x12\x14\n" +
	"\x05ratio\x18\x06 \x01(\x01R\x05ratio\x12\x12\n" +
	"\x04blob\x18\a \x01(\fR\x04blob\x123\n" +
	"\x05color\x18\b \x01(\x0e2\x1d.newblok.test.orders.v1.ColorR\x05color\x123\n" +
	"\x05order\x18\t \x01(\v2\x1d.newblok.test.orders.v1.OrderR\x05order\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x123\n" +
	"\x05lines\x18\v \x03(\v2\x1d.newblok.test.orders.v1.OrderR\x05lines\x12\x17\n" +
	"\x04note\x18\f \x01(\tH\x00R\x04note\x88\x01\x01\x12\x16\n" +
	"\x06counts\x18\r \x03(\x05R\x06countsB\a\n" +
	"\x05_note\"5\n" +
	"\tWithOneof\x12\x0e\n" +
	"\x01a\x18\x01 \x01(\tH\x00R\x01a\x12\x0e\n" +
	"\x01b\x18\x02 \x01(\x05H\x00R\x01bB\b\n" +
	"\x06choice\"\x1e\n" +
	"\n" +
	"WithUint64\x12\x10\n" +
	"\x03big\x18\x01 \x01(\x04R\x03big\"\x89\x01\n" +
	"\aWithMap\x12C\n" +
	"\x06labels\x18\x01 \x03(\v2+.newblok.test.orders.v1.WithMap.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\rWithTimestamp\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"N\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x05child\x18\x02 \x01(\v2\x1c.newblok.test.orders.v1.NodeR\x05child\"\xc0\x04\n" +
	"\x04Wide\x127\n" +
	"\x19field_with_a_long_name_01\x18\x01 \x01(\tR\x14fieldWithALongName01\x127\n" +
	"\x19field_with_a_long_name_02\x18\x02 \x01(\tR\x14fieldWithALongName02\x127\n" +
	"\x19field_with_a_long_name_03\x18\x03 \x01(\tR\x14fieldWithALongName03\x127\n" +
	"\x19field_with_a_long_name_04\x18\x04 \x01(\tR\x14fieldWithALongName04\x127\n" +
	"\x19field_with_a_long_name_05\x18\x05 \x01(\tR\x14fieldWithALongName05\x127\n" +
	"\x19field_with_a_long_name_06\x18\x06 \x01(\tR\x14fieldWithALongName06\x127\n" +
	"\x19field_with_a_long_name_07\x18\a \x01(\tR\x14fieldWithALongName07\x127\n" +
	"\x19field_with_a_long_name_08\x18\b \x01(\tR\x14fieldWithALongName08\x127\n" +
	"\x19field_with_a_long_name_09\x18\t \x01(\tR\x14fieldWithALongName09\x127\n" +
	"\x19field_with_a_long_name_10\x18\n" +
	" \x01(\tR\x14fieldWithALongName10\"8\n" +
	"\x04Rows\x120\n" +
	"\x04rows\x18\x01 \x03(\v2\x1c.newblok.test.orders.v1.WideR\x04rows*=\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOLOR_RED\x10\x01\x12\x0e\n" +
	"\n" +
	"COLOR_BLUE\x10\x022\x9f\x05\n" +
	"\x06Orders\x12F\n" +
	"\x05Place\x12\x1d.newblok.test.orders.v1.Order\x1a\x1e.newblok.test.orders.v1.Placed\x12G\n" +
	"\aInspect\x12\x1d.newblok.test.orders.v1.Kinds\x1a\x1d.newblok.test.orders.v1.Kinds\x12H\n" +
	"\x05Watch\x12\x1d.newblok.test.orders.v1.Order\x1a\x1e.newblok.test.orders.v1.Placed0\x01\x12K\n" +
	"\x06Choose\x12!.newblok.test.orders.v1.WithOneof\x1a\x1e.newblok.test.orders.v1.Placed\x12K\n" +
	"\x05Count\x12\".newblok.test.orders.v1.WithUint64\x1a\x1e.newblok.test.orders.v1.Placed\x12H\n" +
	"\x05Label\x12\x1f.newblok.test.orders.v1.WithMap\x1a\x1e.newblok.test.orders.v1.Placed\x12N\n" +
	"\x05Stamp\x12%.newblok.test.orders.v1.WithTimestamp\x1a\x1e.newblok.test.orders.v1.Placed\x12B\n" +
	"\x04Walk\x12\x1c.newblok.test.orders.v1.Node\x1a\x1c.newblok.test.orders.v1.Node\x12B\n" +
	"\x04Fill\x12\x1c.newblok.test.orders.v1.Rows\x1a\x1c.newblok.test.orders.v1.NodeBFZDgithub.com/well-prado/new-blok/trigger/grpc/internal/orderpb;orderpbb\x06proto3"

var (
	file_orders_proto_rawDescOnce sync.Once
	file_orders_proto_rawDescData []byte
)

func file_orders_proto_rawDescGZIP() []byte {
	file_orders_proto_rawDescOnce.Do(func() {
		file_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)))
	})
	return file_orders_proto_rawDescData
}

var file_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orders_proto_goTypes = []any{
	(Color)(0),                    // 0: newblok.test.orders.v1.Color
	(*Order)(nil),                 // 1: newblok.test.orders.v1.Order
	(*Placed)(nil),                // 2: newblok.test.orders.v1.Placed
	(*Kinds)(nil),                 // 3: newblok.test.orders.v1.Kinds
	(*WithOneof)(nil),             // 4: newblok.test.orders.v1.WithOneof
	(*WithUint64)(nil),            // 5: newblok.test.orders.v1.WithUint64
	(*WithMap)(nil),               // 6: newblok.test.orders.v1.WithMap
	(*WithTimestamp)(nil),         // 7: newblok.test.orders.v1.WithTimestamp
	(*Node)(nil),                  // 8: newblok.test.orders.v1.Node
	(*Wide)(nil),                  // 9: newblok.test.orders.v1.Wide
	(*Rows)(nil),                  // 10: newblok.test.orders.v1.Rows
	nil,                           // 11: newblok.test.orders.v1.WithMap.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_orders_proto_depIdxs = []int32{
	1,  // 0: newblok.test.orders.v1.Placed.echo:type_name -> newblok.test.orders.v1.Order
	0,  // 1: newblok.test.orders.v1.Kinds.color:type_name -> newblok.test.orders.v1.Color
	1,  // 2: newblok.test.orders.v1.Kinds.order:type_name -> newblok.test.orders.v1.Order
	1,  // 3: newblok.test.orders.v1.Kinds.lines:type_name -> newblok.test.orders.v1.Order
	11, // 4: newblok.test.orders.v1.WithMap.labels:type_name -> newblok.test.orders.v1.WithMap.LabelsEntry
	12, // 5: newblok.test.orders.v1.WithTimestamp.at:type_name -> google.protobuf.Timestamp
	8,  // 6: newblok.test.orders.v1.Node.child:type_name -> newblok.test.orders.v1.Node
	9,  // 7: newblok.test.orders.v1.Rows.rows:type_name -> newblok.test.orders.v1.Wide
	1,  // 8: newblok.test.orders.v1.Orders.Place:input_type -> newblok.test.orders.v1.Order
	3,  // 9: newblok.test.orders.v1.Orders.Inspect:input_type -> newblok.test.orders.v1.Kinds
	1,  // 10: newblok.test.orders.v1.Orders.Watch:input_type -> newblok.test.orders.v1.Order
	4,  // 11: newblok.test.orders.v1.Orders.Choose:input_type -> newblok.test.orders.v1.WithOneof
	5,  // 12: newblok.test.orders.v1.Orders.Count:input_type -> newblok.test.orders.v1.WithUint64
	6,  // 13: newblok.test.orders.v1.Orders.Label:input_type -> newblok.test.orders.v1.WithMap
	7,  // 14: newblok.test.orders.v1.Orders.Stamp:input_type -> newblok.test.orders.v1.WithTimestamp
	8,  // 15: newblok.test.orders.v1.Orders.Walk:input_type -> newblok.test.orders.v1.Node
	10, // 16: newblok.test.orders.v1.Orders.Fill:input_type -> newblok.test.orders.v1.Rows
	2,  // 17: newblok.test.orders.v1.Orders.Place:output_type -> newblok.test.orders.v1.Placed
	3,  // 18: newblok.test.orders.v1.Orders.Inspect:output_type -> newblok.test.orders.v1.Kinds
	2,  // 19: newblok.test.orders.v1.Orders.Watch:output_type -> newblok.test.orders.v1.Placed
	2,  // 20: newblok.test.orders.v1.Orders.Choose:output_type -> newblok.test.orders.v1.Placed
	2,  // 21: newblok.test.orders.v1.Orders.Count:output_type -> newblok.test.orders.v1.Placed
	2,  // 22: newblok.test.orders.v1.Orders.Label:output_type -> newblok.test.orders.v1.Placed
	2,  // 23: newblok.test.orders.v1.Orders.Stamp:output_type -> newblok.test.orders.v1.Placed
	8,  // 24: newblok.test.orders.v1.Orders.Walk:output_type -> newblok.test.orders.v1.Node
	8,  // 25: newblok.test.orders.v1.Orders.Fill:output_type -> newblok.test.orders.v1.Node
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_orders_proto_init() }
func file_orders_proto_init() {
	if File_orders_proto != nil {
		return
	}
	file_orders_proto_msgTypes[0].OneofWrappers = []any{}
	file_orders_proto_msgTypes[2].OneofWrappers = []any{}
	file_orders_proto_msgTypes[3].OneofWrappers = []any{
		(*WithOneof_A)(nil),
		(*WithOneof_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_proto_goTypes,
		DependencyIndexes: file_orders_proto_depIdxs,
		EnumInfos:         file_orders_proto_enumTypes,
		MessageInfos:      file_orders_proto_msgTypes,
	}.Build()
	File_orders_proto = out.File
	file_orders_proto_goTypes = nil
	file_orders_proto_depIdxs = nil
}
