// Deterministic bindings from the sole canonical proto. npm lock pins generator.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, readdirSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const proto = resolve(root, "../../contract/runtime/runtime.proto");
const scratch = mkdtempSync(resolve(tmpdir(), "blok-node-bindings-"));
const walk = dir => readdirSync(dir, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(resolve(dir, e.name)) : [resolve(dir, e.name)]);
try {
  execFileSync(process.execPath, [resolve(root, "node_modules/@grpc/proto-loader/build/bin/proto-loader-gen-types.js"), "--grpcLib=@grpc/grpc-js", "--longs=String", "--enums=String", "--defaults", "--oneofs", `--outDir=${scratch}`, proto]);
  const files = new Map(walk(scratch).map(file => [relative(scratch, file), "// GENERATED by @grpc/proto-loader 0.8.0; npm run generate. Do not edit.\n" + readFileSync(file, "utf8").replaceAll(proto, "contract/runtime/runtime.proto").replace(/(from ['"])(\.[^'"]+)(['"])/g, "$1$2.js$3")]));
  files.set("proto.sha256", createHash("sha256").update(readFileSync(proto)).digest("hex") + "\n");
  const target = resolve(root, "generated");
  if (process.argv.includes("--check")) {
    const actual = walk(target).map(file => relative(target, file));
    if (actual.length !== files.size || actual.some(file => files.get(file) !== readFileSync(resolve(target, file), "utf8"))) throw new Error("generated_bindings_drift: run npm run generate");
  } else {
    for (const [name, data] of files) { mkdirSync(dirname(resolve(target, name)), { recursive: true }); writeFileSync(resolve(target, name), data); }
    // The owned generated tree has no hand-authored files.
    for (const file of walk(target)) if (!files.has(relative(target, file))) rmSync(file);
  }
} finally { rmSync(scratch, { recursive: true, force: true }); }
