package scaffold

import (
	"bytes"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// frameworkDir is this repository's root, a valid local framework checkout.
func frameworkDir(t *testing.T) string {
	t.Helper()
	dir, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return dir
}

func TestCreateWritesTheDeclaredStarterDeterministically(t *testing.T) {
	for layout, node := range map[string]string{"classic": "runtimes/go/nodes/quote", "unified": "nodes/go/quote"} {
		t.Run(layout, func(t *testing.T) {
			want := []string{
				"README.md", "blok.json", "cmd/shop/main.go", "go.mod",
				"internal/app/app.go", "internal/app/app_test.go",
				node + "/bindings_gen.go", node + "/quote.go", node + "/types.go",
				"workflows/quotes/quotes.go",
			}
			trees := make([]map[string][]byte, 2)
			for i := range trees {
				directory := filepath.Join(t.TempDir(), "shop")
				paths, err := Create(Options{Directory: directory, Module: "example.com/shop", Layout: layout, Framework: Framework{Version: "v0.1.0"}})
				if err != nil {
					t.Fatal(err)
				}
				sorted := append([]string(nil), want...)
				sort.Strings(sorted)
				if strings.Join(paths, ",") != strings.Join(sorted, ",") {
					t.Fatalf("paths=%v; want %v", paths, sorted)
				}
				trees[i] = map[string][]byte{}
				for _, path := range paths {
					content, err := os.ReadFile(filepath.Join(directory, filepath.FromSlash(path)))
					if err != nil {
						t.Fatal(err)
					}
					trees[i][path] = content
				}
			}
			for path, content := range trees[0] {
				if !bytes.Equal(content, trees[1][path]) {
					t.Fatalf("%s differs between two identical scaffolds", path)
				}
			}
			if !bytes.Contains(trees[0]["blok.json"], []byte(`"types": "`+node+`/types.go"`)) {
				t.Fatalf("blok.json does not name the types file:\n%s", trees[0]["blok.json"])
			}
			if !bytes.HasPrefix(trees[0][node+"/bindings_gen.go"], []byte("// Code generated by new-blok generate; DO NOT EDIT.")) {
				t.Fatal("bindings are not marked generated")
			}
		})
	}
}

func TestGoModReachesTheFramework(t *testing.T) {
	directory := filepath.Join(t.TempDir(), "byversion")
	if _, err := Create(Options{Directory: directory, Framework: Framework{Version: "v0.0.0-20261005000000-abcdefabcdef"}}); err != nil {
		t.Fatal(err)
	}
	mod, _ := os.ReadFile(filepath.Join(directory, "go.mod"))
	if want := "module example.com/byversion\n\ngo 1.27.0\n\nrequire github.com/well-prado/new-blok v0.0.0-20261005000000-abcdefabcdef\n"; string(mod) != want {
		t.Fatalf("go.mod=%q; want %q", mod, want)
	}
	local := filepath.Join(t.TempDir(), "bydir")
	if _, err := Create(Options{Directory: local, Framework: Framework{Dir: frameworkDir(t)}}); err != nil {
		t.Fatal(err)
	}
	mod, _ = os.ReadFile(filepath.Join(local, "go.mod"))
	if !strings.Contains(string(mod), "replace github.com/well-prado/new-blok => ") || !strings.Contains(string(mod), frameworkDir(t)) {
		t.Fatalf("go.mod does not replace the framework with the checkout:\n%s", mod)
	}
}

func TestCreateRejectsBadSelectionsBeforeWriting(t *testing.T) {
	notCheckout := t.TempDir()
	for name, options := range map[string]Options{
		"runtime":                {Runtime: "node"},
		"trigger":                {Triggers: []string{"worker"}},
		"layout":                 {Layout: "flat"},
		"name":                   {Name: "my-app"},
		"module":                 {Module: "./relative"},
		"framework module":       {Module: "github.com/well-prado/new-blok/app"},
		"no framework":           {Framework: Framework{}},
		"both frameworks":        {Framework: Framework{Version: "v0.1.0", Dir: notCheckout}},
		"not a checkout":         {Framework: Framework{Dir: notCheckout}},
		"version is not version": {Framework: Framework{Version: "latest"}},
	} {
		t.Run(name, func(t *testing.T) {
			directory := filepath.Join(t.TempDir(), "app")
			if options.Framework == (Framework{}) && name != "no framework" {
				options.Framework = Framework{Version: "v0.1.0"}
			}
			options.Directory = directory
			if _, err := Create(options); err == nil {
				t.Fatal("accepted")
			}
			if _, err := os.Stat(directory); !os.IsNotExist(err) {
				t.Fatalf("a rejected selection created the target: %v", err)
			}
		})
	}
}

func TestCreateNeverOverwrites(t *testing.T) {
	directory := t.TempDir()
	existing := filepath.Join(directory, "go.mod")
	if err := os.WriteFile(existing, []byte("module mine\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Create(Options{Directory: directory, Framework: Framework{Version: "v0.1.0"}}); err == nil || !strings.Contains(err.Error(), "not empty") {
		t.Fatalf("err=%v; want a refusal", err)
	}
	if content, _ := os.ReadFile(existing); string(content) != "module mine\n" {
		t.Fatalf("existing file changed: %q", content)
	}
}
