// Package generate creates deterministic typed field and argument bindings from Go source.
package generate

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"sort"
	"strings"
)

const flowImport = "github.com/well-prado/new-blok/flow"

type Options struct {
	Package string
}

func Source(source []byte, options Options) ([]byte, error) {
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, "input.go", source, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse source: %w", err)
	}
	packageName := file.Name.Name
	if options.Package != "" {
		packageName = options.Package
	}
	if packageName == "" || packageName == "main" {
		return nil, fmt.Errorf("unsupported package name %q", packageName)
	}
	config := &types.Config{Importer: nil}
	info := &types.Info{Defs: map[*ast.Ident]types.Object{}}
	if _, err := config.Check(packageName, fileSet, []*ast.File{file}, info); err != nil {
		return nil, fmt.Errorf("type check source: %w", err)
	}

	typesToGenerate := make([]*types.Named, 0)
	for _, declaration := range file.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok.String() != "type" {
			continue
		}
		for _, specification := range general.Specs {
			typeSpec := specification.(*ast.TypeSpec)
			if !ast.IsExported(typeSpec.Name.Name) {
				continue
			}
			object, ok := info.Defs[typeSpec.Name].(*types.TypeName)
			if !ok {
				continue
			}
			named, ok := object.Type().(*types.Named)
			if !ok {
				continue
			}
			if _, ok := named.Underlying().(*types.Struct); ok {
				typesToGenerate = append(typesToGenerate, named)
			}
		}
	}
	sort.Slice(typesToGenerate, func(i, j int) bool { return typesToGenerate[i].Obj().Name() < typesToGenerate[j].Obj().Name() })

	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by new-blok generate; DO NOT EDIT.\npackage %s\n\nimport %q\n\n", packageName, flowImport)
	for _, named := range typesToGenerate {
		structure := named.Underlying().(*types.Struct)
		name := named.Obj().Name()
		fmt.Fprintf(&output, "type %sRef struct { value flow.Ref[%s] }\n\n", name, name)
		fmt.Fprintf(&output, "func %sFields(value flow.Ref[%s]) %sRef { return %sRef{value: value} }\n\n", name, name, name, name)
		for index := 0; index < structure.NumFields(); index++ {
			field := structure.Field(index)
			if !field.Exported() || field.Embedded() {
				continue
			}
			fieldType, err := renderType(field.Type())
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, field.Name(), err)
			}
			fieldName := field.Name()
			fmt.Fprintf(&output, "func (r %sRef) %s() flow.Ref[%s] { return flow.Select[%s, %s](r.value, %q) }\n\n", name, fieldName, fieldType, name, fieldType, lowerFirst(fieldName))
		}
		fmt.Fprintf(&output, "type %sArgs struct {\n", name)
		for index := 0; index < structure.NumFields(); index++ {
			field := structure.Field(index)
			if !field.Exported() || field.Embedded() {
				continue
			}
			fieldType, err := renderType(field.Type())
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, field.Name(), err)
			}
			fmt.Fprintf(&output, "\t%s flow.Ref[%s]\n", field.Name(), fieldType)
		}
		output.WriteString("}\n\n")
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func renderType(typeValue types.Type) (string, error) {
	switch value := typeValue.(type) {
	case *types.Basic:
		if value.Kind() == types.UntypedNil {
			return "", fmt.Errorf("unsupported type %s", value)
		}
		return value.Name(), nil
	case *types.Named:
		if value.Obj().Pkg() == nil {
			return value.Obj().Name(), nil
		}
		return value.Obj().Name(), nil
	case *types.Pointer:
		inner, err := renderType(value.Elem())
		if err != nil {
			return "", err
		}
		return "*" + inner, nil
	case *types.Slice:
		inner, err := renderType(value.Elem())
		if err != nil {
			return "", err
		}
		return "[]" + inner, nil
	default:
		return "", fmt.Errorf("unsupported type %s", typeValue)
	}
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
